### ISSUE TITLE
if map to guest is set to bad users, authenticated users are not able to connect

### ISSUE THREAD

**Issue by BrainSlayer** [cifsd-team/ksmbd-tools#100]
https://github.com/cifsd-team/smbd-tools/blob/e6fb2bde6a7ec5d8c19e5cee58c70739a8064cb4/lib/management/tree_conn.c#L117

this check should only be valid for unauthenicated/guest users, but not to authenticated. otherwise they are refused to connect if map to guest is set to bad users and the share is valid only for authenticated users

the following propsal will fix this

       if (((req->account_flags & SMBD_USER_FLAG_BAD_PASSWORD ||
            req->account_flags & SMBD_USER_FLAG_GUEST_ACCOUNT) &&
           global_conf.map_to_guest == SMBD_CONF_MAP_TO_GUEST_BAD_USER)  &&
            !test_share_flag(share, SMBD_SHARE_FLAG_PIPE) &&
            !test_share_flag(share, SMBD_SHARE_FLAG_GUEST_OK)) {

**Comment by namjaejeon** [comment]
Ah, Thanks for your suggestion, I will check it.

**Comment by gibeomii-kim** [comment]
hello, BrainSlayer.
Thanks for your suggestion,
But I'm not sure which is the issue.

do you mean that it is occurring the issue to try network drive connection by registered users after bad user tries network drive connection?
But this is the same of Samba.

Is it an issue related to bad password setting?
I want you to tell me the issue once more accurately.
Thanks you :)

**Comment by Andy2244** [comment]
> But this is the same of Samba.

Its not the same settings work on samba4.

> Is it an issue related to bad password setting?
> I want you to tell me the issue once more accurately.

The issue is we use this template as our default: https://github.com/openwrt/packages/blob/master/net/smbd-tools/files/smb.conf.template

If you now try to connect with a actual user via user/password that has a passdb entry the connection fails. If we remove `map to guest = Bad User` the connection works.

The setting should make no difference to valid users and should only affect guest access, yet it seems to also effect normal users.

**Comment by BrainSlayer** [comment]
i tested a working samba4 config with smbd and was running into this issue, the proposal i made, fixed this issue. so the check should only be made for unauthenticated users. but with the current code the check made for all users, authenticated or not. so if the share is set to "guest ok = no" or no guest ok is set, but the global config has map to guest = bad user, it will always fail for this share, even if the user is authenticated. only guest users should be considered for this check (or users with bad password). otherwise is simply not possible to connect as authenticated if bad logins are treated as guest accounts

**Comment by namjaejeon** [comment]
Pushed the patch to next branch(https://github.com/cifsd-team/smbd-tools/commit/e7ecf8267a704cdb098a3a2ac6c47df2b84ca5c4).

**Comment by namjaejeon** [comment]
Pushed the patch to master from next.
Thanks for your report and solution!!
