### ISSUE TITLE
does not compile under glibc

### ISSUE THREAD

**Issue by neheb** [cifsd-team/ksmbd-tools#167]
https://downloads.openwrt.org/snapshots/faillogs/arc_archs/packages/ksmbd-tools/compile.txt

Needs to have -lpthread added to linker flags.

**Comment by namjaejeon** [comment]
Sorry, I don't understand why this build issue comes out suddenly. build is okay with my local and travis-ci test. And ksmbd-tool doen't include pthread.h.

**Comment by neheb** [comment]
If I had to guess, it's because we link to glib statically.

**Comment by namjaejeon** [comment]
okay, Could you please send the patch to fix ? I think that you can confirm problem is fixed on your system.

**Comment by neheb** [comment]
Actually I don't think this is correct. We're overriding GLIB_LIBS. Probably incorrectly. Closing.
