### ISSUE TITLE
group items such as @group1 don't work in "valid users"

### ISSUE THREAD

**Issue by iamwudy** [cifsd-team/ksmbd-tools#200]
smb.conf as
[aaa]
path = /tmp
valid users = @group1,@users,user3
write list = @group1

then in /etc/group :
users:x:100:user1
group1:x:1000:user2

both user1 & user2 can not read aaa
user3 can read aaa

but smb.conf as
[aaa]
path = /tmp
valid users = user1,user2
write list = user1
it works

**Comment by namjaejeon** [comment]
Okay, Just report bug to us ? or is there any usecase for this in your product ?

**Comment by iamwudy** [comment]
Our company uses Role-Based Access Control Model in file service.
One user for each staff, one group for each role.
one staff has several roles, one role can access several directories.
We use "groupmems -g Group1 -a User1" and "valid users = @Group1" to permit User1 accessing the shared directories,
and it works in samba
But now "valid users = @Group1" don't work in ksmbd. We need this feature.
Could you fix this bug or add this feature?

**Comment by namjaejeon** [comment]
I hope you will solve the problem yourself. and contribute the patch to ksmbd-tools.

**Comment by iamwudy** [comment]
There is my patch[@group.diff.txt](https://github.com/cifsd-team/ksmbd-tools/files/9330944/%40group.diff.txt)! BUT use carefully, in that:
1. parse_list() in lib/management/share.c will be restricted to parse valid users/invalid users/read list/write list/admin users only.
2. user names in ksmbd should identical to which in system, because only users in system are recorded in /etc/group.
3. Testing in production environment has not been implemented, in that the code is coded in my sick rest.

**Comment by namjaejeon** [comment]
@iamwudy Thanks for your change! Could you please send a PR(pull request) to ksmbd-tools to be reviewed and tested ?

**Comment by iamwudy** [comment]
I did it! My first PR on github.
Now it is running in the department which I am working in.
It serves about 40 staffs, correctly accepts valid group members, and rejects invalid groups.

**Comment by Ramalama2** [comment]
Hi, im not sure if this worked once.

But i have the exact same issue.
A user in "valid users" works without issues.
A group prefixed by @ doesnt work in "valid users".

Im using v3.5.2 with kernel 6.8.0-41-generic (ubuntu 24.04).
I had to use the Package from Ubuntu 24.10, because the ksmbd-tools package in 24.04 is broken, its not installable because there is something missing in the package that errors out dpkg.

Cheers

**Comment by Ramalama2** [comment]
```
[global]
	guest account = nobody
	map to guest = bad user
	netbios name = PROFICASH
	server max protocol = SMB3_11
	server min protocol = SMB2_10
	server string = Proficash Server
	workgroup = WORKGROUP

	; default share parameters
	browseable = yes
	guest ok = no
	hide dot files = yes

[App]
	comment = ProfiCash Programm
	path = /server/proficash
	browseable = yes
	guest ok = no
	force group = sambashare
	valid users = muster.benutzer
	write list = muster.benutzer
	create mask = 0660
	directory mask = 0770
```

Aside from the fact that @sambagroup in valid users or write list doesnt work.
If the directory "/server/proficash" is not owned by `muster.benutzer : sambashare`, but instead `root : sambashare` you dont have write access either.

Tbh, ksmbd is a really great idea, but its definitively not usable in this state.
Performance is not great compared to samba either, its around the same, i would say even a little bit slower.
Really Sad! Ksmbd is tiny, samba is huge, but yeah in this state its sadly not usable.

Cheers

**Comment by namjaejeon** [comment]
@Ramalama2 Thanks for your report:)
regarding to performance, You need  to check your kernel debug configuration on single channel of ksmbd. It will affect read/write performance. As you said, the gap of read/write performance between samba and ksmbd on single channel will be small. there are many other factors as well as read/write in filesystem performance. You need to measure file operations(open,close,readdir,unlink, etc..). I recommend to measure it using fileop in iozone.

and if you use multi-port NIC, You will feel an overwhelming performance difference compared to samba. Many other users have reported this difference to me. and RDMA support, As you know, RDMA performance is superior. Only ksmbd is suppported on linux solution.

Don't just complain and don't try to rely on others like commercial solutions. Open source code is open and free and other users can fix it themselves and contribute.

Anyway, I will check your report soon.

**Comment by namjaejeon** [comment]
@atheik If you have the time, Can you help fix this report ?

**Comment by atheik** [comment]
@namjaejeon,

I have not managed to reproduce this. Did you?

@Ramalama2,

> Aside from the fact that @sambagroup in valid users or write list doesnt work.

How do I reproduce the issues you are having?

<details>
<summary>Exerciser for @(at)group functionality (click the arrow to expand)</summary>

````sh
# shut down the ksmbd server
su -- root -c 'ksmbd.control -s'

# add a system user called issue200
su -- root -c 'useradd issue200'

# create directory /tmp/issue200 as system user issue200
su -- issue200 -c 'mkdir /tmp/issue200'

# add a ksmbd user for system user issue200
ksmbd.adduser -C /tmp/issue200.conf -P /tmp/issue200.db -p mypass -a issue200

# add a ksmbd share called issue200 with path /tmp/issue200
ksmbd.addshare -C /tmp/issue200.conf -P /tmp/issue200.db -o 'path = /tmp/issue200' -a issue200

# run ksmbd and log to this terminal
su -- root -c 'ksmbd.mountd -n2 -C /tmp/issue200.conf -P /tmp/issue200.db &' && sleep 1

# this should succeed - does a share listing
smbclient -U issue200%mypass -c 'dir' //127.0.0.1/issue200
##   .                                   D        0  Sun Sep  1 21:41:53 2024
##   ..                                  D        0  Sun Sep  1 21:42:52 2024
## 
##                 1530654 blocks of size 4096. 1525198 blocks available

# this should fail - creates directory /tmp/issue200/case1
smbclient -U issue200%mypass -c 'mkdir case1' //127.0.0.1/issue200
## NT_STATUS_ACCESS_DENIED making remote directory \case1

# give write permissions to ksmbd user issue200
ksmbd.addshare -C /tmp/issue200.conf -P /tmp/issue200.db -o 'write list = issue200' -u issue200
su -- root -c 'ksmbd.control -r' && sleep 1

# this should succeed - creates directory /tmp/issue200/case2
smbclient -U issue200%mypass -c 'mkdir case2' //127.0.0.1/issue200

# add a system group called issue200supp
su -- root -c 'groupadd issue200supp'

# give write permissions to ksmbd users whose system users are in system group issue200supp
ksmbd.addshare -C /tmp/issue200.conf -P /tmp/issue200.db -o 'write list = @issue200supp' -u issue200
su -- root -c 'ksmbd.control -r' && sleep 1

# this should fail - creates directory /tmp/issue200/case3
smbclient -U issue200%mypass -c 'mkdir case3' //127.0.0.1/issue200
## NT_STATUS_ACCESS_DENIED making remote directory \case3

# give share access to ksmbd users whose system users are in system group issue200supp
ksmbd.addshare -C /tmp/issue200.conf -P /tmp/issue200.db -o 'valid users = @issue200supp' -u issue200
su -- root -c 'ksmbd.control -r' && sleep 1

# this should fail - does a share listing
smbclient -U issue200%mypass -c 'dir' //127.0.0.1/issue200
## [ksmbd.mountd(worker)/33507]: ERROR: treecon: User is not on valid users list
## Bad SMB2 (sign_algo_id=1) signature for message
## [0000] 0A F2 27 CD FB 1D 47 F9   40 49 39 39 54 09 BF C3   ..'...G. @I99T...
## [0000] 99 5E 52 CC AE FD 63 7D   CB 76 AA C6 5E BC 65 1F   .^R...c} .v..^.e.
## tree connect failed: NT_STATUS_ACCESS_DENIED

# add system user issue200 to system group issue200supp
su -- root -c 'usermod -aG issue200supp issue200'
su -- root -c 'ksmbd.control -r' && sleep 1

# this should succeed - creates directory /tmp/issue200/case4
smbclient -U issue200%mypass -c 'mkdir case4' //127.0.0.1/issue200

# this should succeed - does a share listing
smbclient -U issue200%mypass -c 'dir' //127.0.0.1/issue200
##   .                                   D        0  Sun Sep  1 21:52:08 2024
##   ..                                  D        0  Sun Sep  1 21:50:04 2024
##   case2                               D        0  Sun Sep  1 21:47:00 2024
##   case4                               D        0  Sun Sep  1 21:52:08 2024
## 
##                 1530654 blocks of size 4096. 1525198 blocks available

# shut down the ksmbd server
su -- root -c 'ksmbd.control -s'

# remove ksmbd configuration
rm /tmp/issue200.conf /tmp/issue200.db
su -- issue200 -c 'rm -r /tmp/issue200'

# remove system user issue200
su -- root -c 'userdel issue200'

# remove system group issue200supp
su -- root -c 'groupdel issue200supp'

````
</details>

> If the directory "/server/proficash" is not owned by muster.benutzer : sambashare, but instead root : sambashare you dont have write access either.

<details>
<summary>Exerciser for force group functionality (click the arrow to expand)</summary>

````sh
# shut down the ksmbd server
su -- root -c 'ksmbd.control -s'

# add a system group called issue200supp
su -- root -c 'groupadd issue200supp'

# create directory /tmp/issue200 as root
su -- root -c 'mkdir /tmp/issue200'

# allow writes to directory through group
su -- root -c 'chmod g+w /tmp/issue200'

# change group of /tmp/issue200 to issue200supp
su -- root -c 'chgrp issue200supp /tmp/issue200'

# add a ksmbd user called issue200
ksmbd.adduser -C /tmp/issue200.conf -P /tmp/issue200.db -p mypass -a issue200

# add a ksmbd share called issue200 with path /tmp/issue200
ksmbd.addshare -C /tmp/issue200.conf -P /tmp/issue200.db -o 'path = /tmp/issue200' -a issue200

# allow read-write access
ksmbd.addshare -C /tmp/issue200.conf -P /tmp/issue200.db -o 'read only = no' -u issue200

# map ksmbd users to system group issue200supp
ksmbd.addshare -C /tmp/issue200.conf -P /tmp/issue200.db -o 'force group = issue200supp' -u issue200

# run ksmbd and log to this terminal
su -- root -c 'ksmbd.mountd -n2 -C /tmp/issue200.conf -P /tmp/issue200.db &' && sleep 1

# this should succeed - creates directory /tmp/issue200/case5
smbclient -U issue200%mypass -c 'mkdir case5' //127.0.0.1/issue200

# this should succeed - does a share listing
smbclient -U issue200%mypass -c 'dir' //127.0.0.1/issue200
##   .                                   D        0  Sun Sep  1 23:14:54 2024
##   ..                                  D        0  Sun Sep  1 23:14:44 2024
##   case5                               D        0  Sun Sep  1 23:14:54 2024
## 
##                 1530654 blocks of size 4096. 1526185 blocks available

# shut down the ksmbd server
su -- root -c 'ksmbd.control -s'

# remove ksmbd configuration
rm /tmp/issue200.conf /tmp/issue200.db
su -- root -c 'rm -r /tmp/issue200'

# remove system group issue200supp
su -- root -c 'groupdel issue200supp'

````
</details>

**Comment by namjaejeon** [comment]
@atheik Oops, I'm sorry for calling you without checking it. Same result for me. I have to ask the reporter how to reproduce it exactly.
@Ramalama2 Please share how to reproduce it at detail.

**Comment by atheik** [comment]
@namjaejeon,

No problem. Please feel free to ask me if you think I can help.

**Comment by namjaejeon** [comment]
@atheik Always thanks for your help and works!

**Comment by Ramalama2** [comment]
> @Ramalama2 Thanks for your report:) regarding to performance, You need to check your kernel debug configuration on single channel of ksmbd. It will affect read/write performance. As you said, the gap of read/write performance between samba and ksmbd on single channel will be small. there are many other factors as well as read/write in filesystem performance. You need to measure file operations(open,close,readdir,unlink, etc..). I recommend to measure it using fileop in iozone.
> 
> and if you use multi-port NIC, You will feel an overwhelming performance difference compared to samba. Many other users have reported this difference to me. and RDMA support, As you know, RDMA performance is superior. Only ksmbd is suppported on linux solution.
> 
> Don't just complain and don't try to rely on others like commercial solutions. Open source code is open and free and other users can fix it themselves and contribute.
> 
> Anyway, I will check your report soon.

Hey thanks for the reply!
About open-source, dont understand me wrong, i really do like ksmbd, actually im sad because i have to switch back to samba. Unusefull in this state sounds harsh, but its sadly the truth. Especially because of this bug i described above.
Another point is VSS, but this is not something thats really used by widespread people.
But here for me essential, as all storages in my environments are based on zfs, so i provide let's say VSS for free everywhere.

RDMA is amazing! But i don't know any client-pc that supports RDMA, i have no Switches even in a big Company that supports RDMA/RoCE, mostly we are using 25/100GBe switches from Microtik because they support MLAG at least.
We don't even have nics that suport RDMA, the best i can offer is an Intel 810 100gbe nic, which lacks RDMA either.

Anyway, im actually a huge fan of ksmbd, its just too limiting atm, sorry.

@namjaejeon 
I will post the entire config/os and so on a bit later, just need to drive now for shopping, sorry.
Thanks for investigations a lot!

**Comment by Ramalama2** [comment]
Hi sorry @namjaejeon , it took a little longer yesterday, but to reproduce the issue:

OS: Ubuntu 24.04.1
Kernel: 6.8.0-41-generic
ksmbd-tools: 3.5.2-3

Repository:
```
/etc/apt/sources.list.d/ksmbd-tools.list
deb http://archive.ubuntu.com/ubuntu/ oracular main universe
```

Ksmbd Config:
```
/etc/apt/preferences.d/ksmbd
Package: *
Pin: release n=oracular
Pin-Priority: 50

Package: ksmbd-tools
Pin: release n=oracular
Pin-Priority: 900
```

The Rpository is needed, because the default ksmbd-tools Package version from Ubuntu 24.04 Noble is broken and can't be installed. (There is another github issue about this)

```
/etc/ksmbd/ksmbd.conf
[global]
	guest account = nobody
	map to guest = bad user
	netbios name = PROFICASH
	server max protocol = SMB3_11
	server min protocol = SMB2_10
	server string = Proficash Server
	workgroup = WORKGROUP

	; default share parameters
	browseable = yes
	guest ok = no
	hide dot files = yes

[App]
	comment = ProfiCash Programm
	path = /server/proficash
	browseable = yes
	guest ok = no
	force group = sambashare
	valid users = @sambashare
	write list = @sambashare
	create mask = 0660
	directory mask = 0770
```

Folder Permissions:
```
ls -lah /server/
total 28K
drwxr-xr-x  3 root root       4.0K Aug 31 00:23 .
drwxr-xr-x 23 root root       4.0K Aug 31 00:23 ..
drwxrwx--- 12 root sambashare  20K Aug 31 03:59 proficash
```

Users:
```
cat /etc/ksmbd/ksmbdpwd.db
max.mustermann:d61WAp/R0HbHyc1S5robAg==
```
```
cat /etc/passwd | grep max
max.mustermann:x:1000:1000::/home/max.mustermann:/usr/sbin/nologin
```

**How does it work with Ksmbd?**
It works instantly if i exchange valid `users = @sambashare` & `write list = @sambashare` to `users = max.mustermann` & `write list = max.mustermann`
No other changes needed!


**How does it work with Samba?**
```
[global]
	workgroup = WORKGROUP
	server string = Proficash Server
	netbios name = PROFICASH
	disable netbios = yes
	log file = /var/log/samba/log.%m
	max log size = 1000
	logging = file
	panic action = /usr/share/samba/panic-action %d
	server role = standalone
	map to guest = bad user
	guest account = nobody
	server min protocol = SMB2_10

[App]
	comment = ProfiCash Programm
	path = /server/proficash
	browseable = yes
	guest ok = no
	force group = sambashare
	valid users = +sambashare
	write list = +sambashare
	create mask = 0660
	directory mask = 0770
```

If needed i can Provide logs.
But this should be replicatable im 100% sure!

Cheers

**Comment by atheik** [comment]
@Ramalama2,

Please also post the output of:
```sh
grep sambashare /etc/group
```

**Comment by Ramalama2** [comment]
> ```shell
> grep sambashare /etc/group
> ```

grep sambashare /etc/group
sambashare:x:1000:

**Comment by Ramalama2** [comment]
> @Ramalama2,
> 
> Please also post the output of:
> 
> ```shell
> grep sambashare /etc/group
> ```

Im not sure why i camed so late to the idea.....
but i downgraded to ksmbd-tools 3.4.9-1 (From Ubuntu Mantic)

And this version works with groups without issues....

**Comment by atheik** [comment]
@Ramalama2,

> grep sambashare /etc/group
> `sambashare:x:1000:`

You have no users in your `sambashare` group.
Exactly what users do you think your `valid users = @sambashare` and `write list = @sambashare` should then refer to?

**Comment by Ramalama2** [comment]
> > @Ramalama2,
> > Please also post the output of:
> > ```shell
> > grep sambashare /etc/group
> > ```
> 
> Im not sure why i camed so late to the idea..... but i downgraded to ksmbd-tools 3.4.9-1 (From Ubuntu Mantic)
> 
> And this version works with groups without issues....

Wrong info, sorry, i had still max.mustermann in the config and thought i had @sambashare.



> @Ramalama2,
> 
> > grep sambashare /etc/group
> > `sambashare:x:1000:`
> 
> You have no users in your `sambashare` group. Exactly what users do you think your `valid users = @sambashare` and `write list = @sambashare` should then refer to?

cat /etc/passwd | grep max
max.mustermann:x:1000:1000::/home/max.mustermann:/usr/sbin/nologin

grep sambashare /etc/group
sambashare:x:1000:

i do have max.mustermann in the sambashare group...

**Comment by atheik** [comment]
@Ramalama2,

> Here even simpler:
> 
> ```
> root@proficash:~# groups max.mustermann
> max.mustermann : sambashare
> ```
> 
> i do have max.mustermann in the sambashare group...

So the primary group of `max.mustermann` is `sambashare` rather than a group called `max.mustermann` as is typical. And when you add new system users you want to use with Samba or ksmbd, you create them such that they all have the same primary group? In other words, rather than have a supplementary group into which you add your users, you instead create multiple users with the exact same GID?

In ksmbd-tools we look at the `user_list` field of the group for the list of users.
So your `/etc/group` entry would look like this:
```
sambashare:x:1000:john.doe,jane.doe,max.mustermann
```

You can add `max.mustermann` into the `sambashare` supplementary group with:
```sh
usermod -aG sambashare max.mustermann
```

Please check that the above modification gets you the behavior you expect so that we are on the same page.

**Comment by Ramalama2** [comment]
> @Ramalama2,
> 
> > Here even simpler:
> > ```
> > root@proficash:~# groups max.mustermann
> > max.mustermann : sambashare
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > i do have max.mustermann in the sambashare group...
> 
> So the primary group of `max.mustermann` is `sambashare` rather than a group called `max.mustermann` as is typical. And when you add new system users you want to use with Samba or ksmbd, you create them such that they all have the same primary group? In other words, rather than have a supplementary group into which you add your users, you instead create multiple users with the exact same GID?
> 
> In ksmbd-tools we look at the `user_list` field of the group for the list of users. So your `/etc/group` entry would look like this:
> 
> ```
> sambashare:x:1000:john.doe,jane.doe,max.mustermann
> ```
> 
> You can add `max.mustermann` into the `sambashare` supplementary group with:
> 
> ```shell
> usermod -aG sambashare max.mustermann
> ```
> 
> Please check that the above modification gets you the behavior you expect so that we are on the same page.

Yes exactly, im adding users the minimal way, without an own group.
Because they are all just for samba anyway and i dont want them or need them or their groups anywhere else.
If it would be possible, i wouldn't even add them to linux, but its neccessary for the file rights sadly xD

However, i tested with supplimentary group sambashare:
```
groups max.mustermann
alexander.kaplan : max.mustermann sambashare
```

And that works without any issues xD
FINALLY, thanks for the hint!

However Samba doesnt need a supplimentary group, primary group is fine there, that why i didn't even thought of that.
Could you implement a way to combine all groups for matching? So that the primary group doesnt get ignored?

Cheers & Thanks!

**Comment by atheik** [comment]
I have yet to check it, but if Samba's behavior does match the exerciser, then this patch should be OK.

<details>
<summary>[PATCH] ksmbd-tools: add users who have @group as their primary group (click the arrow to expand)</summary>

````diff
From 2412863f1d9d8e333dfa012d74668fbbdbd9af39 Mon Sep 17 00:00:00 2001
From: =?UTF-8?q?Atte=20Heikkil=C3=A4?= <atteh.mailbox@gmail.com>
Date: Mon, 9 Sep 2024 18:26:03 +0300
Subject: [PATCH] ksmbd-tools: add users who have @group as their primary group
MIME-Version: 1.0
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 8bit

It was reported that Samba supports a use case where @group is treated as a
primary group. Rather than only adding users who have it as a supplementary
group, we now also add users who have the group as their primary group. Since
POSIX does not offer a good way of doing this, we iterate through the system
password database and look for users with the matching GID.

Signed-off-by: Atte Heikkilä <atteh.mailbox@gmail.com>
---
 tools/management/share.c | 20 +++++++++++++++++---
 1 file changed, 17 insertions(+), 3 deletions(-)

diff --git a/tools/management/share.c b/tools/management/share.c
index de75599..3729c9a 100644
--- a/tools/management/share.c
+++ b/tools/management/share.c
@@ -370,15 +370,29 @@ static void add_users_map(struct ksmbd_share *share,
 		if (**pp == 0x00)
 			continue;
 		if (**pp == '@') {
-			struct group *e = getgrnam(*pp + 1);
+			struct group *ge = getgrnam(*pp + 1);
+			g_autoptr(GPtrArray) ge_gid_users =
+				g_ptr_array_new_with_free_func(g_free);
+			struct passwd *pe;
 
-			if (!e) {
+			if (!ge) {
 				pr_err("Can't get group file entry for `%s'\n",
 				       *pp + 1);
 				continue;
 			}
 
-			add_users_map(share, map, g_strdupv(e->gr_mem));
+			setpwent();
+			while ((pe = getpwent()))
+				if (pe->pw_gid == ge->gr_gid)
+					gptrarray_printf(ge_gid_users,
+							 "%s",
+							 pe->pw_name);
+			endpwent();
+
+			add_users_map(share, map, gptrarray_to_strv(ge_gid_users));
+			ge_gid_users = NULL;
+
+			add_users_map(share, map, g_strdupv(ge->gr_mem));
 			continue;
 		}
 
-- 
2.46.0


````
</details>

<details>
<summary>Exerciser for new @group functionality (click the arrow to expand)</summary>

````sh
# shut down the ksmbd server
su -- root -c 'ksmbd.control -s'

# create directory /tmp/issue200 as root
su -- root -c 'mkdir /tmp/issue200'

# allow writes to directory through group
su -- root -c 'chmod g+w /tmp/issue200'

# add a system group called issue200
su -- root -c 'groupadd issue200'

# change group of /tmp/issue200 to issue200
su -- root -c 'chgrp issue200 /tmp/issue200'

# add system users called issue200{a,b} with primary group issue200
su -- root -c 'useradd -g issue200 issue200a'
su -- root -c 'useradd -g issue200 issue200b'

# add a system user called issue200c
su -- root -c 'useradd issue200c'

# add system user issue200c to system group issue200
su -- root -c 'usermod -aG issue200 issue200c'

# add ksmbd users for system users issue200{a,b,c}
ksmbd.adduser -C /tmp/issue200.conf -P /tmp/issue200.db -p mypass1 -a issue200a
ksmbd.adduser -C /tmp/issue200.conf -P /tmp/issue200.db -p mypass2 -a issue200b
ksmbd.adduser -C /tmp/issue200.conf -P /tmp/issue200.db -p mypass3 -a issue200c

# add a ksmbd share called issue200 with path /tmp/issue200
ksmbd.addshare -C /tmp/issue200.conf -P /tmp/issue200.db -o 'path = /tmp/issue200' -a issue200

# give write permissions to ksmbd users whose system users are in system group issue200
ksmbd.addshare -C /tmp/issue200.conf -P /tmp/issue200.db -o 'write list = @issue200' -u issue200

# run ksmbd and log to this terminal
su -- root -c 'ksmbd.mountd -n2 -C /tmp/issue200.conf -P /tmp/issue200.db &' && sleep 1

# these should succeed - creates directories /tmp/issue200/case{6,7}
smbclient -U issue200a%mypass1 -c 'mkdir case6' //127.0.0.1/issue200
smbclient -U issue200b%mypass2 -c 'mkdir case7' //127.0.0.1/issue200

# this should fail - creates directory /tmp/issue/case8
smbclient -U issue200c%mypass3 -c 'mkdir case8' //127.0.0.1/issue200
## NT_STATUS_ACCESS_DENIED making remote directory \case8

# map ksmbd users to system group issue200
ksmbd.addshare -C /tmp/issue200.conf -P /tmp/issue200.db -o 'force group = issue200' -u issue200
su -- root -c 'ksmbd.control -r' && sleep 1

# this should succeed - creates directory /tmp/issue/case9
smbclient -U issue200c%mypass3 -c 'mkdir case9' //127.0.0.1/issue200

# this should succeed - does a share listing
smbclient -U issue200c%mypass3 -c 'dir' //127.0.0.1/issue200
##   .                                   D        0  Mon Sep  9 18:32:35 2024
##   ..                                  D        0  Mon Sep  9 18:32:18 2024
##   case6                               D        0  Mon Sep  9 18:32:04 2024
##   case7                               D        0  Mon Sep  9 18:32:06 2024
##   case9                               D        0  Mon Sep  9 18:32:35 2024
## 
##                 1530654 blocks of size 4096. 1529391 blocks available

# shut down the ksmbd server
su -- root -c 'ksmbd.control -s'

# remove ksmbd configuration
rm /tmp/issue200.conf /tmp/issue200.db
su -- root -c 'rm -r /tmp/issue200'

# remove system users issue200{a,b}
su -- root -c 'userdel issue200a'
su -- root -c 'userdel issue200b'

# remove system group issue200
su -- root -c 'groupdel issue200'

# remove system user issue200c
su -- root -c 'userdel issue200c'

````
</details>

**Comment by namjaejeon** [comment]
@atheik Applied your patch:) Thanks for your work!
@Ramalama2 First, Thanks for your report  and check:), Let me know if you have other issues while using ksmbd.

**Comment by atheik** [comment]
@namjaejeon,

I said in https://github.com/cifsd-team/ksmbd-tools/issues/200#issuecomment-2338842053 that the patch should be OK if Samba's behavior matches the exerciser. I said also that I have not checked if that is the case. Since you applied the patch, did you check it?

**Comment by namjaejeon** [comment]
@atheik No, I thought that @Ramalama2 have checked it and gave his confirmation to us.
@Ramalama2 You have directly checked this patch. right ?

**Comment by Ramalama2** [comment]
No i didnt checked the patch.
The confirmation was only for the "supplimentary" groups.

But i can check the patch today in the evening, when im home 🙈

**Comment by atheik** [comment]
@namjaejeon,

Here is a patch to a bug I introduced in commit cb106ed.

<details>
<summary>[PATCH] ksmbd-tools: prevent recursive @group lookup (click the arrow to expand)</summary>

````diff
From 8e5936611b0257a3e1ab5997233a3e1e664c1754 Mon Sep 17 00:00:00 2001
From: =?UTF-8?q?Atte=20Heikkil=C3=A4?= <atteh.mailbox@gmail.com>
Date: Sat, 14 Sep 2024 03:58:11 +0300
Subject: [PATCH] ksmbd-tools: prevent recursive @group lookup
MIME-Version: 1.0
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 8bit

A non-standards-compliant login name that begins with an @ sign may
be used e.g. by giving --badname to useradd(8). Users with such names
cannot be used in parameters that take a user list, since the leading
@ sign is reserved for @group, but we still allow such names elsewhere.
If an @group lookup resolves into such a name, treat it now as a user
name rather than another @group. The bug fixed here was introduced in
commit cb106ed.

Signed-off-by: Atte Heikkilä <atteh.mailbox@gmail.com>
---
 tools/management/share.c | 30 +++++++++++++++++++++---------
 1 file changed, 21 insertions(+), 9 deletions(-)

diff --git a/tools/management/share.c b/tools/management/share.c
index 3729c9a..962c8eb 100644
--- a/tools/management/share.c
+++ b/tools/management/share.c
@@ -357,7 +357,8 @@ struct ksmbd_share *shm_lookup_share(char *name)
 
 static void add_users_map(struct ksmbd_share *share,
 			  enum share_users map,
-			  char **names)
+			  char **names,
+			  int skip_group)
 {
 	char **pp;
 
@@ -369,7 +370,7 @@ static void add_users_map(struct ksmbd_share *share,
 
 		if (**pp == 0x00)
 			continue;
-		if (**pp == '@') {
+		if (**pp == '@' && !skip_group) {
 			struct group *ge = getgrnam(*pp + 1);
 			g_autoptr(GPtrArray) ge_gid_users =
 				g_ptr_array_new_with_free_func(g_free);
@@ -389,10 +390,16 @@ static void add_users_map(struct ksmbd_share *share,
 							 pe->pw_name);
 			endpwent();
 
-			add_users_map(share, map, gptrarray_to_strv(ge_gid_users));
+			add_users_map(share,
+				      map,
+				      gptrarray_to_strv(ge_gid_users),
+				      1);
 			ge_gid_users = NULL;
 
-			add_users_map(share, map, g_strdupv(ge->gr_mem));
+			add_users_map(share,
+				      map,
+				      g_strdupv(ge->gr_mem),
+				      1);
 			continue;
 		}
 
@@ -641,35 +648,40 @@ static void process_share_conf_kv(struct ksmbd_share *share, char *k, char *v)
 	if (shm_share_config(k, KSMBD_SHARE_CONF_VALID_USERS)) {
 		add_users_map(share,
 			      KSMBD_SHARE_VALID_USERS_MAP,
-			      cp_get_group_kv_list(v));
+			      cp_get_group_kv_list(v),
+			      0);
 		return;
 	}
 
 	if (shm_share_config(k, KSMBD_SHARE_CONF_INVALID_USERS)) {
 		add_users_map(share,
 			      KSMBD_SHARE_INVALID_USERS_MAP,
-			      cp_get_group_kv_list(v));
+			      cp_get_group_kv_list(v),
+			      0);
 		return;
 	}
 
 	if (shm_share_config(k, KSMBD_SHARE_CONF_READ_LIST)) {
 		add_users_map(share,
 			      KSMBD_SHARE_READ_LIST_MAP,
-			      cp_get_group_kv_list(v));
+			      cp_get_group_kv_list(v),
+			      0);
 		return;
 	}
 
 	if (shm_share_config(k, KSMBD_SHARE_CONF_WRITE_LIST)) {
 		add_users_map(share,
 			      KSMBD_SHARE_WRITE_LIST_MAP,
-			      cp_get_group_kv_list(v));
+			      cp_get_group_kv_list(v),
+			      0);
 		return;
 	}
 
 	if (shm_share_config(k, KSMBD_SHARE_CONF_ADMIN_USERS)) {
 		add_users_map(share,
 			      KSMBD_SHARE_ADMIN_USERS_MAP,
-			      cp_get_group_kv_list(v));
+			      cp_get_group_kv_list(v),
+			      0);
 		return;
 	}
 
-- 
2.46.0


````
</details>

**Comment by namjaejeon** [comment]
@atheik Applied it to #master. Thanks!

**Comment by namjaejeon** [comment]
> But i can check the patch today in the evening, when im home 🙈

@Ramalama2 Okay, Thanks for your help:)

**Comment by atheik** [comment]
@namjaejeon,

With [the exerciser](https://github.com/cifsd-team/ksmbd-tools/issues/200#issuecomment-2338842053), creating directory `case8` fails in ksmbd but succeeds in Samba.

In ksmbd, even though system user `issue200c` has `issue200` as a supplementary group, it gets `NT_STATUS_ACCESS_DENIED` when attempting to create the directory.

In Samba, creating the directory succeeds:
```
total 0
drwxrwxr-x  6 root      issue200  120 Sep 16 15:20 .
drwxrwxrwt 12 root      root      300 Sep 16 15:20 ..
drwxr-xr-x  2 issue200a issue200   40 Sep 16 15:20 case6
drwxr-xr-x  2 issue200b issue200   40 Sep 16 15:20 case7
drwxr-xr-x  2 issue200c issue200c  40 Sep 16 15:20 case8
drwxr-xr-x  2 issue200c issue200   40 Sep 16 15:20 case9

```

This is not related to the @(at)group functionality, since the behavior is the same with just `path = /tmp/issue200` and `read only = no`.

**Comment by namjaejeon** [comment]
@atheik Okay, Let me take a look. Thanks!
