### ISSUE TITLE
official debian package

### ISSUE THREAD

**Issue by alexmyczko** [cifsd-team/ksmbd-tools#218]
it got rejected for:

I also wonder whether a software that uses md4 shall be added to the archive ...

**Comment by namjaejeon** [comment]
Hm.. What is problem using md4 ?

**Comment by alexmyczko** [comment]
or according to https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=561a1cf57535154f094f31167a9170197caae686

is it still needed?

**Comment by namjaejeon** [comment]
> or according to https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=561a1cf57535154f094f31167a9170197caae686

This patch is to remove md4 use in ksmbd kernel module, not add it. ksmbd-tools is not related with this one. And ksmbd-tools included ksmbd.mountd as well as ksmbd.adduser. If there is no ksmbd.mountd, user can not run ksmbd server. User need to launch ksmbd.mountd in ksmbd-tools to run ksmbd kernel server.

**Comment by alexmyczko** [comment]
so without md4 it will not work right?

**Comment by hclee** [comment]
@alexmyczko 


> so without md4 it will not work right? [Y/n]
Yes, md4 is needed.

**Comment by namjaejeon** [comment]
@alexmyczko without md4, ksmbd will work fine. ksmbd no longer need md4.

**Comment by namjaejeon** [comment]
@alexmyczko ksmbd I said is ksmbd in mainline kernel, not out of tree ksmbd at github. out of tree ksmbd contain smb1 protocol suppprt, it need md4 library in kernel.

**Comment by alexmyczko** [comment]
so if i wanted to disable smb1 support i can get rid of md4?

**Comment by namjaejeon** [comment]
I would like to know what ksmbd is used ? ksmbd in mainline kernel or ksmbd in this github ?

**Comment by namjaejeon** [comment]
ksmbd in mainline kernel doesn't support SMB1.

**Comment by alexmyczko** [comment]
of course i mean ksmbd-tools where the issue is filed at sorry for the confusion

**Comment by namjaejeon** [comment]
Ah.. ksmbd and ksmbd-tools are different... if you are saying ksmbd-tools, not ksmbd kernel module for md4, I have to change my words. ksmbd-tools contain own md4 library.
Could you please tell me why you want to remove md4 for packaging in debian ?

**Comment by alexmyczko** [comment]
https://en.wikipedia.org/wiki/MD4?wprov=sfti1

*I* am not the who wants to remove it, *they* do not want it in Debian for good reasons (security):
https://ftp-master.debian.org

**Comment by namjaejeon** [comment]
Okay, Samba must also need md4 hash for NT password encryption. cifs client kernel module also. It makes no sense that samba is fine and ksmbd is not for md4 use.

**Comment by namjaejeon** [comment]
Please read this discussion threads : https://www.spinics.net/lists/linux-cifs/msg22555.html

**Comment by namjaejeon** [comment]
Can you please share what's going on ?

**Comment by alexmyczko** [comment]
all fine, let's see 2nd round of NEW queue... (i had the license wrong for md4* files)

**Comment by alexmyczko** [comment]
it just entered sid!
