### ISSUE TITLE
system crash when copying big file on exFAT filesystem

### ISSUE THREAD

**Issue by Kenny0793** [cifsd-team/ksmbd-tools#219]
Hi All,

      When copying big file(2G) on exFAT filesystem. I found that explorer.exe will pop up an error message, 
After clicking 'Cancel', the system will crash. The crash logs see attachment.
       After investigating further, I found that the issue was caused by calling ksmbd_vfs_truncate in the function set_end_of_file_info. I simply disable it, the big file(>4g) can be copied successfully.  Can you tell me the side effects of disabling it? or any other good solutions to recommend? thanks.
      root@mygateway:~# ksmbd.mountd -V
      ksmbd-tools version : 3.3.4

**Comment by Kenny0793** [comment]
[](url
<img width="341" alt="copying_2g_files_error" src="https://user-images.githubusercontent.com/89910682/142823068-8ca45c50-fe5e-41df-a941-06c31c2b3a4a.png">
)

**Comment by Kenny0793** [comment]
[exFAT_copy_2g_crash.txt](https://github.com/cifsd-team/ksmbd-tools/files/7579062/exFAT_copy_2g_crash.txt)

**Comment by namjaejeon** [comment]
Could you please try to check the issue after applying the following change ?

```
diff --git a/smb2pdu.c b/smb2pdu.c
index 92bd096..ea61722 100644
--- a/smb2pdu.c
+++ b/smb2pdu.c
@@ -5789,7 +5789,9 @@ static int set_end_of_file_info(struct ksmbd_work *work, struct ksmbd_file *fp,
         * truncate of some filesystem like FAT32 fill zero data in
         * truncated range.
         */
-       if (inode->i_sb->s_magic != MSDOS_SUPER_MAGIC) {
+#define EXFAT_SUPER_MAGIC      0x2011BAB0UL
+       if (inode->i_sb->s_magic != MSDOS_SUPER_MAGIC &&
+           inode->i_sb->s_magic != EXFAT_SUPER_MAGIC) {
                ksmbd_debug(SMB, "filename : %s truncated to newsize %lld\n",
                            fp->filename, newsize);
                rc = ksmbd_vfs_truncate(work, NULL, fp, newsize);
```

**Comment by Kenny0793** [comment]
Yes, It is ok. can you explain a bit more why exFAT has such issue? only skipping it, no any side effects, is it right?

**Comment by namjaejeon** [comment]
exfat is not supporting sparse file, which means truncate() will fill zero out to all range in disk. If you copy 2GB file, windows client send some command to move end offset. and ksmbd call ftruncate(). but It will take a very long time to zero out 2GB in exfat(or FAT). The problem occurs when the Windows client takes too long for a command request and windows timeout occurs.

**Comment by Kenny0793** [comment]
Thanks for the detailed explanation.
