### ISSUE TITLE
The performance cannot exceed that of NFS server. What did I do wrong?

### ISSUE THREAD

**Issue by ceozero** [cifsd-team/ksmbd-tools#220]
I compiled ksmbd on CentOS 8. I found that when reading a lot of data, there will be a lot of ksmbd IO, but it does not occupy CPU and memory, but kswapd will occupy a lot of CPU. There is still a lot of memory left in my server. How should I debug?

How can ksmbd use RDMA on CentOS? Like nfsordma?

nfsordma Maximum hard disk speed  30G/s
nfs           Maximum hard disk speed   20G/s
ksmb       Maximum hard disk speed   11G/s

The speed of the network card is 40g * 4  for lacp ...

`[global]
	netbios name = |NAME|
	server string = |DESCRIPTION|
	workgroup = |WORKGROUP|
	ipc timeout = 20
	deadtime = 15
	map to guest = Bad User
	server multi channel support = yes
	vfs objects = aio_pthread
	aio read size = 1
	aio write size = 1
	strict locking = No
	max open files = 900000
	max active sessions = =10240

[ar]
	comment = arminer
	guest ok = yes
	path = /mnt/ar
	public = yes
	browseable = yes
	writable = yes
	create mask = 0644
	directory mask = 0755
`

![image](https://user-images.githubusercontent.com/22513657/143272555-6a0d1750-adf7-4fa0-98a0-503793746bed.png)
![image](https://user-images.githubusercontent.com/22513657/143272599-21860f6a-0249-400f-89c9-cba4715176ed.png)
![image](https://user-images.githubusercontent.com/22513657/143272635-e722bb1f-ae0e-4c16-ac86-f539d5b0077c.png)

**Comment by hclee** [comment]
> I compiled ksmbd on CentOS 8. I found that when reading a lot of data, there will be a lot of ksmbd IO, but it does not occupy CPU and memory, but kswapd will occupy a lot of CPU. There is still a lot of memory left in my server. How should I debug?
> 

Could you show your /proc/meminfo in the situation?

> How can ksmbd use RDMA on CentOS? Like nfsordma?
> 

If you use cifs as a client, you need to mount cifs with rdma=1.

> nfsordma Maximum hard disk speed 30G/s nfs Maximum hard disk speed 20G/s ksmb Maximum hard disk speed 11G/s
> 
> The speed of the network card is 40g * 4 for lacp ...
> 
> `[global] netbios name = |NAME| server string = |DESCRIPTION| workgroup = |WORKGROUP| ipc timeout = 20 deadtime = 15 map to guest = Bad User server multi channel support = yes vfs objects = aio_pthread aio read size = 1 aio write size = 1 strict locking = No max open files = 900000 max active sessions = =10240
> 
> [ar] comment = arminer guest ok = yes path = /mnt/ar public = yes browseable = yes writable = yes create mask = 0644 directory mask = 0755`
> 
> ![image](https://user-images.githubusercontent.com/22513657/143272555-6a0d1750-adf7-4fa0-98a0-503793746bed.png) ![image](https://user-images.githubusercontent.com/22513657/143272599-21860f6a-0249-400f-89c9-cba4715176ed.png) ![image](https://user-images.githubusercontent.com/22513657/143272635-e722bb1f-ae0e-4c16-ac86-f539d5b0077c.png)

**Comment by ceozero** [comment]
> `If you use cifs as a client, you need to mount cifs with rdma=1.`

RDMA doesn't seem to work. Does the server ksmb need to make any other settings?

![image](https://user-images.githubusercontent.com/22513657/143372397-da8e9db7-9f06-47f3-b3a8-6d00f66e75e2.png)

> Could you show your /proc/meminfo in the situation?

MemTotal:       49402484 kB
MemFree:          546416 kB
MemAvailable:   44375524 kB
Buffers:            1880 kB
Cached:         43570668 kB
SwapCached:            0 kB
Active:           414892 kB
Inactive:       44223708 kB
Active(anon):      16436 kB
Inactive(anon):  1316048 kB
Active(file):     398456 kB
Inactive(file): 42907660 kB
Unevictable:        3072 kB
Mlocked:               0 kB
SwapTotal:             0 kB
SwapFree:              0 kB
Dirty:              1604 kB
Writeback:             0 kB
AnonPages:       1069964 kB
Mapped:           268532 kB
Shmem:            258644 kB
KReclaimable:    1127460 kB
Slab:            1445088 kB
SReclaimable:    1127460 kB
SUnreclaim:       317628 kB
KernelStack:       24048 kB
PageTables:        18788 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:    24701240 kB
Committed_AS:    1631388 kB
VmallocTotal:   34359738367 kB
VmallocUsed:      167952 kB
VmallocChunk:          0 kB
Percpu:            47616 kB
HardwareCorrupted:     0 kB
AnonHugePages:    546816 kB
ShmemHugePages:        0 kB
ShmemPmdMapped:        0 kB
FileHugePages:         0 kB
FilePmdMapped:         0 kB
HugePages_Total:       0
HugePages_Free:        0
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
Hugetlb:               0 kB
DirectMap4k:      430116 kB
DirectMap2M:    12118016 kB
DirectMap1G:    39845888 kB

**Comment by namjaejeon** [comment]
Can you tell us what kernel you are using in CentOS ? If kernel version is too low, cifs client doesn't support RDMA.

**Comment by ceozero** [comment]
> 你能告诉我们你在 CentOS 中使用的是哪个内核版本吗？如果内核版本太低，cifs 客户端不支持 RDMA。
CentOS Stream release 8  __  5.15.4-1.el8.elrepo.x86_64

**Comment by ceozero** [comment]
This is a client error.

![image](https://user-images.githubusercontent.com/22513657/143422874-a69ea89c-5d83-42e9-b4f2-74e7436055ef.png)

**Comment by namjaejeon** [comment]
Can you see transfort_rdma.o object file in your ksmbd directory ?

**Comment by ceozero** [comment]
> Can you see transfort_rdma.o object file in your ksmbd directory ?


not find transfort_rdma.o，

<img width="436" alt="截屏2021-11-25 23 27 24" src="https://user-images.githubusercontent.com/22513657/143468028-376e93c4-f550-409e-a642-3e27447ccb35.png">

**Comment by ceozero** [comment]
It does not seem to have been compiled. . How can I add it to compile?
<img width="436" alt="截屏2021-11-25 23 27 24" src="https://user-images.githubusercontent.com/22513657/143475965-e100ead3-e641-40e6-b1e9-f1efc05317d9.png">

**Comment by mmakassikis** [comment]
If you're using a recent kernel, make sure you have set CONFIG_SMB_SERVER_SMBDIRECT through "make menuconfig".
If you're building a module for an older kernel,  pass that as an argument to make:

> make CONFIG_SMB_SERVER_SMBDIRECT=y

**Comment by ceozero** [comment]
> If you're using a recent kernel, make sure you have set CONFIG_SMB_SERVER_SMBDIRECT through "make menuconfig". If you're building a module for an older kernel, pass that as an argument to make:
> 
> > make CONFIG_SMB_SERVER_SMBDIRECT=y

An error has occurred

<img width="670" alt="截屏2021-11-26 01 28 20" src="https://user-images.githubusercontent.com/22513657/143482954-7e4efc7d-bbe0-497f-9ab1-f45ec0065c1e.png">
<img width="575" alt="截屏2021-11-26 01 28 52" src="https://user-images.githubusercontent.com/22513657/143482961-cb775d97-b1df-4a70-9dc4-90c37ecf3eca.png">

**Comment by namjaejeon** [comment]
We can not understand Chinese. And this is not a technical issue or ksmbd issue, so please do find the way using googling how to build it.

**Comment by namjaejeon** [comment]
or
ksmbd is merged into linux 5.15 kernel. So you can find kernel source of 5.15.4-1-el8.elrepo.x86_64 and turn on ksmbd & rdma in config. and then build kernel and install it.
