### ISSUE TITLE
Can't  build with 5.15 kernel

### ISSUE THREAD

**Issue by LynxChaus** [cifsd-team/ksmbd-tools#221]
Can't build with 5.15 kernel due to removed locks_verify_truncate() from kernel.
Patch is simple - call locks_verify_truncate() only if defined CONFIG_MANDATORY_FILE_LOCKING.

**Comment by mmakassikis** [comment]
Hello,

Do you need SMB1 support ? If you don't, then you can use the code that's already committed in the kernel, i.e: you don't need to checkout and compile code from cifsd-team/ksmbd repo.

**Comment by LynxChaus** [comment]
Yes, i need v1 support. Feed video files to TV-box over encrypted link is overkill.

**Comment by mmakassikis** [comment]
AFAIK, SMB2/SMB3 are not encrypted by default: it depends on what the client/server negotiate at connection time.

Have you measured a speed or cpu usage difference between SMB1 and SMB2 transfers (on an older kernel perhaps) ?

**Comment by namjaejeon** [comment]
@LynxChaus Please check your issue on latest master.

**Comment by LynxChaus** [comment]
@namjaejeon latest master builds without error. Thnx.
