### ISSUE TITLE
Missing spnego_mech.h in official 3.4.3 tarball

### ISSUE THREAD

**Issue by ffontaine** [cifsd-team/ksmbd-tools#224]
The [official 3.4.3 tarball](https://github.com/cifsd-team/ksmbd-tools/releases/download/3.4.3/ksmbd-tools-3.4.3.tar.gz) is missing https://github.com/cifsd-team/ksmbd-tools/blob/master/lib/management/spnego_mech.h resulting in the following build failure if `--enable-krb5` is set:

```
management/spnego.c:25:10: fatal error: spnego_mech.h: No such file or directory
   25 | #include "spnego_mech.h"
      |          ^~~~~~~~~~~~~~~
```

The [official 3.4.2 tarball](https://github.com/cifsd-team/ksmbd-tools/releases/download/3.4.2/ksmbd-tools-3.4.2.tgz) is not affected by this issue.

Full build log:
 - http://autobuild.buildroot.org/results/fa8/fa88c5bc1924dfb352d9b8dddbb7fdbb192a6b07/build-end.log

**Comment by hclee** [comment]
I have written the patch for this. Can you tell me your email address to add Reported-by into commit decription?

**Comment by ffontaine** [comment]
Sure, here it is: 
```
Reported-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
```

**Comment by namjaejeon** [comment]
@hclee I'm assuming I'm not doing anything wrong. Wasn't the build from the original krb5 support? Should we add a build test to travis-CI?

**Comment by hclee** [comment]
> @hclee I'm assuming I'm not doing anything wrong. Wasn't the build from the original krb5 support? 

I cannot understand "Wasn't the build from the original krb5 support?".
This error occurs only in building a release tarball because of not packing spnego_mech.h.
I have sent the patch, https://github.com/cifsd-team/ksmbd-tools/pull/225.

> Should we add a build test to travis-CI?

Yes, It is better to configure with --enable-krb5. I will send a patch.

**Comment by ffontaine** [comment]
Do you plan on releasing 3.4.4 soon or should I just disable krb5 on buildroot for the time being?

**Comment by namjaejeon** [comment]
I am planning to release 3.4.4 release next week. So you can wait or apply this patch(https://github.com/namjaejeon/ksmbd-tools/commit/529a8ce7d82c363909f7ce65e16527af7ba68a59) to ksmbd-tools in your buildbot.

**Comment by ffontaine** [comment]
Great, buildroot will have its next release by the end of February so I can definitely wait, thanks for your feedback.

**Comment by mmakassikis** [comment]
Somewhat related: the Documentation/configuration.txt file is missing from the ksmbd-tools-3.4.3.tar.gz tarball. I don't know if that's intentional

**Comment by namjaejeon** [comment]
@mmakassikis Ah, Thanks for your reporting!

@ffontaine I have repacked ksmbd-tools 3.4.3 version and update release(https://github.com/cifsd-team/ksmbd-tools/releases/tag/3.4.3). Please check it.

**Comment by ffontaine** [comment]
The new tarball doesn't ship any `configure` file (only `configure.ac` is provided). So, `autoreconf` must be run to built it. Except from that, it works.

**Comment by namjaejeon** [comment]
@ffontaine I have release ksmbd/ksmbd-tools 3.4.4 version. please check it.

**Comment by ffontaine** [comment]
Everything is fine in the new release, thanks
