### ISSUE TITLE
Version 3.4.4 fails to start with IPC error messages

### ISSUE THREAD

**Issue by mamarley** [cifsd-team/ksmbd-tools#227]
After upgrading to 3.4.4 (with kernel 5.16.2), the userspace daemon fails to start with:

```
ERROR: Recv() error Input data out of range [-8]
ERROR: WARNING: child process exited abnormally: 29336
ERROR: Fatal IPC error. Terminating. Check dmesg.
ERROR: can't execute kill 29336: No such process
```

Nothing is printed in dmesg. If I revert ea0da00d4d9f801963b52d26cd56eb1026ac6b27, it works normally again.

**Comment by hclee** [comment]
For 3.4.4 tools, the following kernel patch is needed.
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=41dbda16a090

**Comment by mamarley** [comment]
Hmm, OK.  That probably ought to have been mentioned on https://github.com/cifsd-team/ksmbd-tools/releases/tag/3.4.4 then.

**Comment by namjaejeon** [comment]
@mamarley I have sent the patch to stable linux kernel. So if you upgrade 5.16.3(not release yet), It will work with ksmbd-tools 3.4.4. Thanks!

**Comment by mamarley** [comment]
Confirmed, after upgrading to 5.16.3, everything is working again.

**Comment by namjaejeon** [comment]
Thanks for your check!
