### ISSUE TITLE
3.4.4: ksmbd.addshare always fails with "ERROR: share name sanity check failure"

### ISSUE THREAD

**Issue by TheDJVG** [cifsd-team/ksmbd-tools#228]
After #[9ad8231473820354187b99f991cd869c5be356f0](https://github.com/cifsd-team/ksmbd-tools/commit/9ad8231473820354187b99f991cd869c5be356f0#diff-aa514b4490f2e4400850ef952bb4504d062c722092b4ecdb4f5d131dbf5679bc) was merged `ksmbd.addshare` will always return `share name sanity check failure`.

To be honest, looking at the code I'm not 100% how it's supposed to work. From what I can see it should `return 0` if the name is correct, maybe the final return should be changed?

**Comment by namjaejeon** [comment]
You're right. I will fix it. Thanks for your report!

**Comment by namjaejeon** [comment]
Done. https://github.com/cifsd-team/ksmbd-tools/commit/62a957944c8187a9dbbed9fb4f9bf5f97ef5c33d

Thanks!

**Comment by KyleSanderson** [comment]
That's no good. This is broken in Ubuntu Jammy...

**Comment by namjaejeon** [comment]
@KyleSanderson So, how can I help you for this ? Ubuntu package manager should upgrade ksmbd-tools version ?

**Comment by KyleSanderson** [comment]
I had to flip back to retail smbd, the kernel module doesn't appear to work in a containerd environment.
