### ISSUE TITLE
Can the ksmbd service be started via procfs or sysfs?

### ISSUE THREAD

**Issue by maroonpu** [cifsd-team/ksmbd-tools#230]
Hi~
Can the ksmbd service be started via procfs or sysfs, but not only ksmbd.mount?

**Comment by mmakassikis** [comment]
ksmbd.mountd is needed for various things (share listing, authentication, etc). What problem are you trying to solve ?

**Comment by maroonpu** [comment]
When I tried to cross-compile ksmbd-tools, I found that ksmbd-tools does not yet support cross-compilation. Although I solved the problem by compiling it separately, I was curious if I could start ksmbd without using the userspace tools.

**Comment by namjaejeon** [comment]
No, Can not.
