### ISSUE TITLE
Worker process frequently exits with `Recv() error Out of memory [-5]`

### ISSUE THREAD

**Issue by database64128** [cifsd-team/ksmbd-tools#235]
- Client: Windows 11 Build 22621
- ksmbd: 3.4.2, Arch Linux stock kernel 5.17.7
- ksmbd-tools: 3.4.4 from AUR

```
ksmbd[910]: [ksmbd-worker/910]: ERROR: Recv() error Out of memory [-5]
ksmbd[909]: [ksmbd.mountd/909]: ERROR: WARNING: child process exited abnormally: 910
ksmbd[909]: [ksmbd.mountd/909]: ERROR: Fatal IPC error. Terminating. Check dmesg.
ksmbd[909]: [ksmbd.mountd/909]: ERROR: can't execute kill 910: No such process
ksmbd[909]: [ksmbd.mountd/909]: INFO: Exiting. Bye!
```

It says out of memory, even though the system didn't actually run out of memory.

Afterward `ksmbd.service` has to be manually restarted to recover from this.

**Comment by namjaejeon** [comment]
Can you provide how to reproduce this issue to us ?

**Comment by database64128** [comment]
This just happens randomly several times a week on daily use. The client runs Windows 11 Build 22621. The server is on the latest stock kernel of Arch Linux (5.17.7). This usually happens when I'm not actively transferring anything but the client is still connected to the network. I was not able to find any specific method to reliably reproduce.

**Comment by namjaejeon** [comment]
Let me know your ksmbd module and ksmbd-tools version.

**Comment by database64128** [comment]
The ksmbd module 3.4.2 came with the kernel. ksmbd-tools 3.4.4 was built and installed from AUR.

**Comment by namjaejeon** [comment]
> The ksmbd module 3.4.2 came with the kernel. 

Ah, I want to know your kernel version.

**Comment by database64128** [comment]
I mentioned it earlier:

> The server is on the latest stock kernel of Arch Linux (5.17.7). But I've also seen this on previous kernel versions like 5.16.x.

I just edited these info into the issue body so it's easier to find.

**Comment by mmakassikis** [comment]
> ksmbd[909]: [ksmbd.mountd/909]: ERROR: Fatal IPC error. Terminating. Check dmesg.

Can you check if dmesg contains any message from ksmbd when the error occurs ?

**Comment by database64128** [comment]
According to thom311/libnl#104, both NetworkManager and systemd-networkd set their Netlink socket's buffer size to 8MiB to work around the same issue. I'm going to try to do the same thing here and see if this resolves my issue.

**Comment by database64128** [comment]
I can confirm that this issue can be fixed by raising the Netlink socket buffer size. Opened #277 for the fix.
