### ISSUE TITLE
rdma port configure & match

### ISSUE THREAD

**Issue by wangyugui-e16** [cifsd-team/ksmbd-tools#301]
Hi,

It is OK to configure RDMA port in ksmbd-tools?
and how to match smb client and smbd server?

in kernel source, fs/smb/client
#define CIFS_PORT 445
#define SMB_PORT        445
#define SMBD_PORT       5445

in kernel source, fs/smb/server
#define SMB_DIRECT_PORT_INFINIBAND   445
#define SMB_DIRECT_PORT_IWARP                5445

Best Regards

**Comment by wangyugui-e16** [comment]
maybe some releation.

port 20049 is not reported by 'netstat -an' when nfs with rdma=20049?

RoCE v2 4791/udp is not reported by 'netstat -an' too?

**Comment by namjaejeon** [comment]
> It is OK to configure RDMA port in ksmbd-tools?

No, Can't. RDMA port is fixed.

> and how to match smb client and smbd server?

SMB client try to connect with 5445 port first, If it fail, try to connect with 445 port again.
ksmbd server will be opening port as RDMA type.

**Comment by namjaejeon** [comment]
I don't know why you ask it. What is problem ?
