### ISSUE TITLE
Where can I see the logs of ksmbd-tools?

### ISSUE THREAD

**Issue by mengqima** [cifsd-team/ksmbd-tools#306]
Hi @namjaejeon , where can I see the logs of ksmbd-tools?

**Comment by namjaejeon** [comment]
What log do you want to see ?

**Comment by mengqima** [comment]
such as: 
// file: tools.h
#define pr_debug(f, ...)	\
	pr_log(PR_DEBUG, PRDEBUG f, ##__VA_ARGS__)
#define pr_info(f, ...)	\
	pr_log(PR_INFO, PRINF f, ##__VA_ARGS__)
#define pr_err(f, ...)	\
	pr_log(PR_ERROR, PRERR f, ##__VA_ARGS__)
But I can not find the output log if I execute ksmbd.mounted

**Comment by namjaejeon** [comment]
Okay. You need to run ksmbd.mount on nodetach mode. So you can use -n option.

**Comment by namjaejeon** [comment]
Or you can check ksmbd.mount log from /var/syslog if you want to run detach mode.

**Comment by mengqima** [comment]
Thanks, it works.
