### ISSUE TITLE
Error and worker killed repeating with "ERROR: Can't resolve netlink family" in syslog.

### ISSUE THREAD

**Issue by spxak1** [cifsd-team/ksmbd-tools#312]
This is on Fedora 39,``` ksmbd-tools``` compiled from source. 

My ```ksmbd.conf``` only contains one share. The user I've added is a system user too.

As soon as I run ```ksmbd.mount``` I get the correct output: 

~~~
[ksmbd.mountd/106760]: INFO: Started manager
~~~

but the syslog is flogged with this sequence every second:

~~~
Dec 09 21:02:08 ceres ksmbd[106761]: [ksmbd.mountd(manager)/106761]: INFO: Started worker
Dec 09 21:02:08 ceres ksmbd[106860]: [ksmbd.mountd(worker)/106860]: ERROR: Can't resolve netlink family
Dec 09 21:02:08 ceres ksmbd[106761]: [ksmbd.mountd(manager)/106761]: ERROR: Worker killed: Aborted
~~~

I can shut it down with ```ksmbd.control -s```, to which I get:

~~~
[ksmbd.control/106937]: INFO: Terminated mountd
[ksmbd.control/106937]: ERROR: Can't kill ksmbd
~~~

That's as far as I can go. I get nothing on Google for the "ERROR: Can't resolve netlink family" error, so here I am.

Many thanks in advance.

**Comment by atheik** [comment]
@spxak1,

Have you loaded the `ksmbd` kernel module, e.g. with `sudo modprobe ksmbd`?
If your kernel does not have `ksmbd` as a loadable module, then you might choose to install [the out-of-tree ksmbd](https://github.com/cifsd-team/ksmbd).

**Comment by spxak1** [comment]
> @spxak1,
> 
> Have you loaded the `ksmbd` kernel module, e.g. with `sudo modprobe ksmbd`? If your kernel does not have `ksmbd` as a loadable module, then you might choose to install [the out-of-tree ksmbd](https://github.com/cifsd-team/ksmbd).

Ah, you're right. I expected the 6.6.4 kernel to have it, but I now see in the config file  ```# CONFIG_SMB_SERVER is not set
```. So I guess it's left disabled.

Thanks.

**Comment by spxak1** [comment]
I can confirm the issue was indeed the kernel module not being loaded. I have compiled the out of tree module and it works fine. Now looking for a systemd service to start/stop it. Thanks @atheik for the heads up.

**Comment by atheik** [comment]
@spxak1,

> Now looking for a systemd service to start/stop it.

Since you built `ksmbd-tools` yourself (and have new enough systemd), the build system should have installed the `ksmbd.service` unit file in your `systemdsystemunitdir` directory. The unit file supports the usual unit commands (e.g. `systemctl start ksmbd`, `systemctl reload ksmbd`, ...) and handles loading of the kernel module.

**Comment by spxak1** [comment]
> @spxak1,
> 
> > Now looking for a systemd service to start/stop it.
> 
> Since you built `ksmbd-tools` yourself (and have new enough systemd), the build system should have installed the `ksmbd.service` unit file in your `systemdsystemunitdir` directory. The unit file supports the usual unit commands (e.g. `systemctl start ksmbd`, `systemctl reload ksmbd`, ...) and handles loading of the kernel module.

I wrote my own, but you're right, it was compiled (but not installed?). Who knows. Anyway, many thanks for your time.

I now have avahi working most of the times (probably a network issue?) to announce the server to my laptop's nautilus (also Fedora). 

Thanks again.
