### ISSUE TITLE
RDMA from Windows Server 2022 to Debian 12 doesn't work.

### ISSUE THREAD

**Issue by LittleNewton** [cifsd-team/ksmbd-tools#319]
<img width="797" alt="截屏2024-06-08 23 56 44" src="https://github.com/cifsd-team/ksmbd-tools/assets/17793356/9e0dec44-3a6e-470a-bab8-e54de4a1dfe8">

NIC: NVIDIA Mellanox CX6 MCX653106A ECAT ethernet mode
CPU: two machines both use AMD EPYC Gen3
OS: the `ksmbd` server is Debian 12 and the client is Windows Server 2022.

No RDMA traffic and activity is witnessed.

**Comment by namjaejeon** [comment]
You need to check if rdma modules are insmod and SMB_SERVER_SMBDIRECT config is enable first.

**Comment by LittleNewton** [comment]
@namjaejeon 
Thank you for your response. I have several questions.

1. You said, "*You need to check if rdma modules are insmod*". What means `insmod`? Or is it just a typo?
2. My Windows Server has enabled RDMA support and it can establish RDMA communication with other Windows Server systems. If you can, please provide detailed steps to check whether related configs such as`SMB_SERVER_SMBDIRECT` are enabled properly on `ksmbd` side.

Thank you so much.

**Comment by LittleNewton** [comment]
Thank you for your response. :)

Do you mean I should compile `ksmbd` manually because Debian 12 bookworm upstream package source didn't enable  `SMB_SERVER_SMBDIRECT` flag of `ksmbd`?

And the second:

> *Have you ever build and installed linux kernel source before ?*

Yes, I know how to compile a modified kernel and install it.

**Comment by LittleNewton** [comment]
<img width="781" alt="截屏2024-06-10 17 32 02" src="https://github.com/cifsd-team/ksmbd-tools/assets/17793356/af0e5d88-25a5-4f97-84a5-efe29a221205">

Yes, I should turn this flag on firstly.

**Thank you for being so helpful!**

**Comment by LittleNewton** [comment]
After rebuilding the kernel, RDMA is still not enabled.

<img width="1179" alt="image" src="https://github.com/cifsd-team/ksmbd-tools/assets/17793356/c6b88b16-ae89-4527-8019-f27523efec94">

**Comment by namjaejeon** [comment]
Can you capture tcpdump or wireshark dump to check the packets ? I need to check dump at session establishment before read/write test. i.e. you can dump it while login id/password.

**Comment by LittleNewton** [comment]
After using Wireshark to capture the packets, I found only `smb2` traffic! Applying `smb_direct` as the filtering keyword, no packet is captured.

**Comment by LittleNewton** [comment]
<img width="797" alt="image" src="https://github.com/cifsd-team/ksmbd-tools/assets/17793356/131079f1-f076-4989-8166-02c6e2c69a68">

I have enabled the SMB-Direct feature on Windows Server 2022. Also, NICs to run SMB traffic can also support RDMA.

**Comment by namjaejeon** [comment]
> After using Wireshark to capture the packets, I found only smb2 traffic! Applying smb_direct as the filtering keyword, no packet is captured.

I mean you need to dump tcp packets. There is a negotiation stage on tcp before reading/write RDMA.
server should send RDMA information to client on tcp connection. I would like to check this.

**Comment by namjaejeon** [comment]
Remember that other people besides you are using RDMA of ksmbd well.
