### ISSUE TITLE
any plans to support a mdns service to announce the shares?

### ISSUE THREAD

**Issue by Andy2244** [cifsd-team/ksmbd-tools#99]
We just noticed that switching from samba4 to smbd has a small issue regarding browsing/finding the shares aka announcement. On windows i made the wsdd2 service compatible, but for Linux/MacOS/Android samba4 directly uses the avahi api to announce the service/shares.

You have any plans on doing something similar or support a other mdns service via api?
I guess the old custom samba avahi service text file should also work for smbd, but not sure.
```
<?xml version="1.0" standalone='no'?>
<!DOCTYPE service-group SYSTEM "avahi-service.dtd">

<service-group>
  <name replace-wildcards="yes">%h</name>
  <service>
    <type>_smb._tcp</type>
    <port>445</port>
  </service>
</service-group>
```

I also don't remember if this was only showing the device/service or if this allowed to also see the share names.

**Comment by namjaejeon** [comment]
Hi Andy,

> We just noticed that switching from samba4 to smbd 

Samba4 ? not Samba3 ? As I know, openWRT is trying to replace samba3 with smbd.

> You have any plans on doing something similar or support a other mdns service via api?

I didn't know such a service is needed for smb file share. but If it is really needed, smbd should support it also.

> I guess the old custom samba avahi service text file should also work for smbd, but not sure.

Oh, Really thanks:) I will check it,

**Comment by Andy2244** [comment]
> Samba4 ? not Samba3 ? As I know, openWRT is trying to replace samba3 with smbd.

Replace Samba3 yes, but also act as a tiny samba4 drop-in replacement, if speed/size is a issue.

> I didn't know such a service is needed for smb file share. but If it is really needed, smbd should support it also.

Its only needed to find/browse the shares, without knowing the devicename/sharenames/ip. This was handled by netbios for WinXP/Vista7/8 and now is [wsd](https://en.wikipedia.org/wiki/WS-Discovery) for Windows10. This works fine via our wsdd2 service.
On Linux/MacOS we use mdns/Bonjour, but only avahi + samba4 seemed to correctly work, so you can browse the shares via filemanager/finder.

In the past this was done manually via a avahi smb/samba config file, but since samba-4.4 i just build with `--enable-avahi` and the service will inject all needed information's directly into avahi via api. This way it avoids config errors. So if smbd could emulate this, this would be pretty neat.

PS: I will try with a custom avahi config file.

**Comment by Andy2244** [comment]
The main samba avahi code seems tobe just in `avahi_client_callback`, they also handle there special macos timemachine fruit_vfs via avahi.

https://github.com/samba-team/samba/blob/master/source3/smbd/avahi_register.c

**Comment by namjaejeon** [comment]
Thanks for info, I will check it.

**Comment by Andy2244** [comment]
Quick update, just tested the old samba custom service file method with ksmbd and still works.
So i will use this for now, only if the user changes the default smb port (445) or uses a special none hostname as netbios name, the service file wont work, since it needs to reflect those changes. 
That's why the integrated way samba4 directly uses libavahiclient is still better, since it can directly update the service definition at runtime.

**Comment by namjaejeon** [comment]
Yep, I can't affort to work it right now. I will surely do that after fixing urgent issues.
Thanks for your feedback:)

**Comment by mrkiko** [comment]
Out of curiosity - what's the current speed comparisons between ksmbd and knfsd, assuming some NFS tuning?
Thank you very much!!

**Comment by namjaejeon** [comment]
We didn't compare the perforamcne between knfsd and ksmbd. instead, Instead, there is only data compared to samba.(https://www.snia.org/sites/default/files/SDC/2019/presentations/SMB/Jeon_Namjae_Lee_Hyunchul_Introduce_New_In-kernel_SMB3_Server_Called_CIFSD.pdf)
If you are interest in it, You can measure the performance of both kernel servers.

**Comment by mrkiko** [comment]
Thank you very ver much for the pointer!

**Comment by Neustradamus** [comment]
@Andy2244: Have you progressed on it?

**Comment by Andy2244** [comment]
@Neustradamus Not much i can do, we use the old avahi textfile still.

**Comment by ematsumiya** [comment]
I could work on this. I've done something very similar to nvme-cli.

**Comment by namjaejeon** [comment]
@ematsumiya Sound great! Thanks!
